runtime: nodejs20
network:
  session_affinity: true
readiness_check:
  path: "/health"
  check_interval_sec: 60
  timeout_sec: 20
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300